/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Attachments: typeof import('vue-aurora-x')['Attachments']
    Bubble: typeof import('vue-aurora-x')['Bubble']
    Button: typeof import('vue-aurora-x')['Button']
    Demo_a: typeof import('./components/Bubble/demos/demo_a.vue')['default']
  }
}
