/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Attachments: typeof import('./src/components/Attachments/index.vue')['default']
    Bubble: typeof import('./src/components/Bubble/index.vue')['default']
    BubbleList: typeof import('./src/components/BubbleList/index.vue')['default']
    Config: typeof import('./src/components/Config/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    Loading: typeof import('./src/components/BubbleList/loading.vue')['default']
    Typewriter: typeof import('./src/components/Typewriter/index.vue')['default']
  }
}
