name: 发布npm包

on:
  push:
    branches: [main]
    paths:
      - 'packages/components/**'
      - '.changeset/**'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # 获取完整历史以支持changesets
    
    - name: 安装pnpm
      uses: pnpm/action-setup@v3
      with:
        version: 10.9.0
    
    - name: 设置Node.js环境
      uses: actions/setup-node@v3
      with:
        node-version: '22'
        registry-url: 'https://registry.npmjs.org'
        cache: 'pnpm'
    
    - name: 安装依赖
      run: pnpm install
    
    - name: 版本更新和发布
      id: changesets
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "github-actions@github.com"
        pnpm run build:components
        pnpm run version
        pnpm run release
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}